### ISSUE TITLE
Repeated kalite virtualenv install error 

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab#2146] opened 2020-01-13 18:37 UTC
http://paste.debian.net/1125855
The last line of the paste suggests that there is a mismatch between python2 and python3 -- which I do not understand.

**Comment by holta** [comment] 2020-01-13 19:28
This is duplicate of #2139, that @jvonau has helped with overnight.  Please see that ticket.

**Closed as completed by holta** 2020-01-13 19:28 UTC
Labels: bug, duplicate
