### ISSUE TITLE
Calibre Installation failure

### ISSUE THREAD

**Issue by Piflyer** [iiab/iiab#831] opened 2018-06-09 22:26 UTC
### Expected behavior and actual behavior.
I was expecting to finish downloading steps 1-9, When in step 9, the Calibre-serve.service keeps failing.
### Steps to reproduce the problem.
Follow instructions on a Raspberry Pi 3b+, either from scratch, or  line 20 app download.
### Specifications like the version of the IIAB, operating system version, or hardware details.
Version Today and Last week.

**Comment by holta** [comment] 2018-06-10 00:55
Calibre 3.24 is the culprit but does 3.25 now fix the problem possibly, as @jvonau  and @kananigit hoped, when all of us confirmed this bug Thursday 2 days ago?  Thankfully .deb's for Calibre 3.25 were released yesterday:

http://raspbian.raspberrypi.org/raspbian/pool/main/c/calibre/

So we need to test the above.  Using http://FAQ.IIAB.IO item 22 to upgrade Calibre for those who can test in place (or a fresh install on RPi 3 B+ or RPi 3...)

**Comment by holta** [comment] 2018-06-10 00:57
Clarif that this bug affects both IIAB 6.5 and 6.6/master

**Comment by Piflyer** [comment] 2018-06-10 01:02
It effected the 6.5, and I tried the one curl program with 20 sever apps, and still got the same result

**Comment by Piflyer** [comment] 2018-06-10 01:11
There is nothing in 6.6

**Comment by holta** [comment] 2018-06-10 01:14
> It effected the 6.5, and I tried the one curl program with 20 sever apps, and still got the same result

Have you had a chance to try installing Calibre 3.25 instead of 3.24 yet?

As confirmed by `apt -a list calibre` after running `apt update` when walking thru the script (https://github.com/iiab/iiab/blob/master/scripts/calibre-install-latest-rpi.sh) by hand?

PS a temporary workaround (until Calibre re-stabilizes for RPi) is to run the Debian script instead: https://github.com/iiab/iiab/blob/master/scripts/calibre-install-latest.sh

**Comment by Piflyer** [comment] 2018-06-10 01:20
Somehow, it's not calibre itself, but starting with systems is the problem.

**Comment by Piflyer** [comment] 2018-06-10 01:21
Meant system and systemctl

**Comment by holta** [comment] 2018-06-10 01:27
> I got calibre 2.75.1 for some reason

That's normal (from the OS) if the 2-step Calibre installation fails halfway through.

Keep Calibre 2.75.1 in place (if possible?) and then try the above-mentioned Debian script `calibre-install-latest.sh`

**Comment by Piflyer** [comment] 2018-06-10 01:29
I'll try to get it back ny installing it and updating it from there.

**Comment by Piflyer** [comment] 2018-06-10 02:14
How do you run the script?

**Comment by holta** [comment] 2018-06-10 02:49
> How do you run the script?

Try:

cd /opt/iiab/iiab
sudo scripts/calibre-install-latest.sh

**Comment by Piflyer** [comment] 2018-06-10 02:50
Hi, do I return to the twenty app server after again?

**Comment by Piflyer** [comment] 2018-06-10 02:53
I continued with the ./iiab-install

**Comment by Piflyer** [comment] 2018-06-10 02:56
It failed on DansGuardian

**Comment by holta** [comment] 2018-06-10 03:01
> It failed on DansGuardian

Can you paste in a photo here?  Or post the error using http://fpaste.org or similar?

**Comment by Piflyer** [comment] 2018-06-10 03:01
`TASK [network : Enable DansGuardian] *********************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not find the requested service dansguardian: host"}
	to retry, use: --limit @/opt/iiab/iiab/iiab-stages.retry

PLAY RECAP ***********************************************************************************************************
127.0.0.1                  : ok=84   changed=33   unreachable=0    failed=1   
`

**Comment by Piflyer** [comment] 2018-06-10 03:03
And then It told me this `root@box:/opt/iiab/iiab#    ./iiab-install
Placed /etc/ansible/facts.d/local_facts.fact into position.
Found Kernel 4.14.34-v7+
Found Ansible 2.5.4
Extracted STAGE=9 (counter) from /etc/iiab/iiab.env

EXITING: STAGE (counter) in /etc/iiab/iiab.env shows Stage 9 Is Already Done.
Use './iiab-install --reinstall' to force running all Stages 0-9.
Use './iiab-install --debug' to run Stage 0, followed by Stages 3-9.
Use './runtags' to run a single Stage or Tag or Role.
Use './iiab-network' to run Network sections.
root@box:/opt/iiab/iiab# 
`

**Comment by holta** [comment] 2018-06-10 07:00
@Piflyer oops this ticket of yours was closed automatically by PR #833 when I merged that.  That fix should work, but I wanted your other questions answered too, if possible!

**Comment by Piflyer** [comment] 2018-06-10 13:28
Somehow, it’s set true and true.

**Comment by Piflyer** [comment] 2018-06-10 13:35
I can’t get into root, it’s telling me that sudo: /usr/bin/sudo must be owned by uid 0 and must have the setuid  bit set.

**Comment by holta** [comment] 2018-06-10 13:53
> I can’t get into root, it’s telling me that sudo: /usr/bin/sudo must be owned by uid 0 and must have the setuid bit set

1) `sudo su -` works in general.
2) Have you protected Raspbian, by changing user pi's password?  You should!  As many Raspbian systems are penetrated by Bitcoin viruses etc.
3) A fresh install onto a fresh Raspbian OS now works ( from http://download.iiab.io/6.5/ ) if you can perhaps try again?

**Comment by Piflyer** [comment] 2018-06-10 14:07
I’all try to get a fresh download of raspbian

**Comment by Piflyer** [comment] 2018-06-12 01:36
Thanks for your help! I was able to successfully get iiab working after a fresh start. The script worked flawlessly! However, is it possible to make the script on my Raspberry Pi 3 B+ on my Pi zero without having the computer in panic mode? Thanks

**Comment by holta** [comment] 2018-06-12 02:18
> is it possible to make the script on my Raspberry Pi 3 B+ on my Pi zero without having the computer in panic mode?

I'm not understanding the question.  Can you explain more?

Aside: we normally use an RPi 3 (or 3 B+) to prepare the microSD — and then later move the finalized microSD into an RPi Zero W.

**Comment by holta** [comment] 2018-06-12 04:18
> I was able to successfully get iiab working after a fresh start. The script worked flawlessly!

Thanks much @Piflyer for confirming.

I'm closing this issue now, with the Calibre issue now solved (please open a new ticket with your new question, Thanks!)

**Closed as completed by holta** 2018-06-12 04:18 UTC
Labels: bug, help wanted

**Comment by Piflyer** [comment] 2018-06-12 12:05
I tired doing that, but the computer said that it wanted to kill init. What do I do?

**Comment by holta** [comment] 2018-06-12 12:36
> the computer said that it wanted to kill init

Open a new ticket with a complete description of the problem.

Photograph the screen and use the journalctl command to grab all systems logs from the timeframe in question.

**Comment by holta** [comment] 2018-06-21 06:11
UNDERLYING CLARIF of this tkt (#831) &mdash; the key failure during install of Calibre 3.24.x and 3.25 appears to have been:
```
The following packages have unmet dependencies:
 calibre : Depends: python-pyqt5 (>= 5.10.1+dfsg-2) but 5.10.1+dfsg-1+rpi1 is to be installed
E: Unable to correct problems, you have held broken packages.
```
Hopefully Calibre forums will shed more light on the root cause &mdash; helping all to avoid such multi-week time wasters in future &mdash; please all who can contribute to this important ongoing thread on [Calibre and calibre-server on Raspberry Pi](https://www.mobileread.com/forums/showthread.php?t=299808) so that kids literally everywhere also have the chance to use Calibre and modern books.
