### ISSUE TITLE
IIAB Visual Identity

### ISSUE THREAD

**Issue by arky** [iiab/iiab#383] opened 2017-10-08 16:27 UTC
Add Internet-in-a-Box (IIAB) brand identity to all landing pages. This might include a logo and matching color palette.  The logo could be animated gif logo/motion graphic to convey the purpose of the project. 

The purpose of task is to increase brand recognition of IIAB.

**Comment by holta** [comment] 2017-10-08 16:53
Don't get frightened away!  But do also see:

IIAB logo - call for designs
http://iiab.io/t/iiab-logo-call-for-designs/32

**Comment by holta** [comment] 2017-11-22 00:30
> IIAB logo - call for designs
http://iiab.io/t/iiab-logo-call-for-designs/32

All logos were lost (as organized over many months by @darkenvy & others!) due to the very sad loss of our Discourse forums on the http://iiab.io server.

@m-anish is working to see if these can be recovered from backup/disk in Delhi, India.

Am deferring this tkt to IIAB 6.6 when we'll know a lot more.

**Comment by holta** [comment] 2018-05-13 03:11
Ref #789

**Comment by arky** [comment] 2018-08-31 12:30
Adding this as UI/UX task list for #1055

**Comment by holta** [comment] 2019-11-01 17:07
This is largely a duplicate of tkt #842 so I'm closing: let's consolidate the discussion in one place!

**Closed as completed by holta** 2019-11-01 17:07 UTC
Labels: duplicate, enhancement, good 1st issue
