### ISSUE TITLE
ubuntu18 smoke test failure

### ISSUE THREAD

**Issue by georgejhunt** [iiab/iiab#811] opened 2018-05-21 17:25 UTC
This is on an Ubuntu18, no admin-console, reinstall. I could fix it by hard coding /etc/netplan/50-cloud-init.yaml as file name. But it's really in Jerry's court

2018-05-21 16:01:57,295 p=25358 u=root |  TASK [network : Figure out netplan file name on Ubuntu 18] *************************************************************************************************************************
2018-05-21 16:01:57,535 p=25358 u=root |  changed: [127.0.0.1]
2018-05-21 16:01:57,572 p=25358 u=root |  TASK [network : Supply static template] ********************************************************************************************************************************************
2018-05-21 16:01:57,830 p=25358 u=root |  fatal: [127.0.0.1]: FAILED! => {"msg": "Failed to get information on remote file (/etc/netplan/50-cloud-init.yaml\n50-cloud-init.yaml.23723.2018-05-12@23:42:45~\n50-cloud-init.yaml.27151.2018-05-12@23:50:59~\n50-cloud-init.yaml\n50-cloud-init.yaml.23723.2018-05-12@23:42:45~\n50-cloud-init.yaml.27151.2018-05-12@23:50:59~\n50-cloud-init.yaml\n50-cloud-init.yaml.23723.2018-05-12@23:42:45~\n50-cloud-init.yaml.27151.2018-05-12@23:50:59~\n50-cloud-init.yaml\n50-cloud-init.yaml.23723.2018-05-12@23:42:45~\n50-cloud-init.yaml.27151.2018-05-12@23:50:59~): File name too long"}
2018-05-21 16:01:57,835 p=25358 u=root |  	to retry, use: --limit @/opt/iiab/iiab/iiab-stages.retry

root@box:/opt/iiab/iiab# ll /etc/netplan/
total 20
-rw-r--r-- 1 root root 292 May 13 17:25  50-cloud-init.yaml
-rw-r--r-- 1 root root 575 May 12 22:09  50-cloud-init.yaml.23723.2018-05-12@23:42:45~
-rw-r--r-- 1 root root 576 May 12 23:42  50-cloud-init.yaml.27151.2018-05-12@23:50:59~
-rw-r--r-- 1 root root 292 May 21 04:19 '50-cloud-init.yaml'$'\n''50-cloud-init.yaml.23723.2018-05-12@23:42:45~'$'\n''50-cloud-init.yaml.27151.2018-05-12@23:50:59~'
-rw-r--r-- 1 root root 292 May 21 13:57 '50-cloud-init.yaml'$'\n''50-cloud-init.yaml.23723.2018-05-12@23:42:45~'$'\n''50-cloud-init.yaml.27151.2018-05-12@23:50:59~'$'\n''50-cloud-init.yaml'$'\n''50-cloud-init.yaml.23723.2018-05-12@23:42:45~'$'\n''50-cloud-init.yaml.27151.2018-05-12@23:50:59~'
root@box:/opt/iiab/iiab#

**Comment by holta** [comment] 2018-05-21 17:35
@jvonau is this addressed by PR #810 possibly?

**Comment by jvonau** [comment] 2018-05-21 17:48
Ok I see what the issue is, there are old backups present in /etc/netplan/ from earlier testing. The current routine doesn't backup the old config files now, so this should not occur going forward. Could you clean out the stale backups and retry please.

**Comment by georgejhunt** [comment] 2018-05-21 18:06
that fixed the smoke test failure -- I guess it's cockpit error, and not a
problem

**Comment by holta** [comment] 2018-05-21 18:07
> that fixed the smoke test failure -- I guess it's cockpit error, and not a
problem

Should I document this somewhere, so others avoid this prob?

(What do they need to avoid doing if so?)

**Comment by jvonau** [comment] 2018-05-21 18:26
Won't hurt, an early tester might get bit by the stale backups.

**Closed as completed** 2018-05-22 17:31 UTC
Labels: bug
