### ISSUE TITLE
scripts/ansible does not upgrade or issue any message

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#457] opened 2017-10-24 18:27 UTC
deb 9 vm with ansible 2.2.0.0
latest master - scripts/ansible
terminates quickly with no message
is this expected?

**Comment by holta** [comment] 2017-10-24 19:40
Can you use Ansible 2.4.0 per Step 5 of our [Do Everything from Scratch](https://github.com/iiab/iiab/wiki/IIAB-Installation#do-everything-from-scratch) installation instructions?  (That Josh Dennis helped us refine for Debian 9 over the past month.)

**Comment by tim-moody** [comment] 2017-10-24 21:26
root@debian9base:/opt/iiab/iiab# ansible --version
ansible 2.2.0.0
  config file = /opt/iiab/iiab/ansible.cfg
  configured module search path = ['/usr/share/ansible']
root@debian9base:/opt/iiab/iiab# apt purge ansible
Reading package lists... Done
Building dependency tree
Reading state information... Done
**Package 'ansible' is not installed, so not removed**
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by holta** [comment] 2017-10-24 21:29
Is it possible 2.2.0 got installed onto Debian 9.1 (or whatever you have) thru pip or some other means than the OS's own "apt install ansible" etc?

(Any idea how 2.2.0 got there?)

**Comment by tim-moody** [comment] 2017-10-24 21:32
I think it got there from the previous version of scripts/ansible

**Comment by holta** [comment] 2017-10-24 21:34
Makes sense.  We have not focused on the installed base, as this has not been a concern to date.

But I do agree with your suggestion that scripts/ansible should clarify matters for "Experts" who become attached to obscure/buggy/older versions of Ansible for their own reasons...and as such we need a PSA right there at the command line...to make clear to them how to extricate...as we all know "overly experienced" sysadmins are people too :-) who need to be able to recover from their own secret sauce per https://github.com/iiab/iiab/wiki/IIAB-Installation#expert-mode (!)

**Comment by tim-moody** [comment] 2017-10-24 21:35
it's not a matter of attachment. there is no way to upgrade

**Comment by holta** [comment] 2017-10-24 21:36
There must be a way to remove Ansible 2.2.0

Unfortunately I'm not the expert )-:

Maybe @georgejhunt & @jvonau & @arky know?

**Comment by tim-moody** [comment] 2017-10-24 21:37
and, btw, this was the official means of installing ansible. it's just that iiab changed afterwards and the changed script is unable to undo what its predecessor did.

**Comment by tim-moody** [comment] 2017-10-24 21:37
see above

**Comment by holta** [comment] 2017-10-24 21:42
When exactly was Ansible 2.2.0 installed (on Debian 9.1 I presume) to help others understand the lineage of what you're working on?  Since 6.4 almost a month ago, we've asked that installers avoid "apt install ansible" and install Ansible 2.4.0 directly using scripts/ansible &mdash; are we talking about a system that predates that?

**Comment by holta** [comment] 2017-10-24 22:11
Yesterday I installed all 5 version of Ansible {2.0, 2.1, 2.2, 2.3, 2.4} on Ubuntu 16.04 LTS to experiment with each (on the very same system) and that is extremely fast+easy using PPA's from launchpad.net

I apologize I'm far less familiar with Debian!

But likely/possibly "apt -a list ansible" can be helpful on Debian too, in managing similar quick/pitstop changes between different versions of Ansible on Debian likewise?

**Comment by tim-moody** [comment] 2017-10-24 22:37
pip uninstall ansible got rid of it (I guess it wasn't a distro package)

now scripts/ansible runs

**Comment by jvonau** [comment] 2017-10-24 22:38
> terminates quickly with no message

Thanks for taking this step, fresh installs were the priority, now to backtrack and cover the corner cases in upgrades.  The scripts looks if ansible-playbook is installed and if installed looks at what version is installed, finding version 2.2.0.0 should echo the current version and force a pip upgrade to version 2.4.0. Think I can reproduce the pip installed ansible-2.2.0.0 layout and see if I can reproduce this. Given that 2.2.0.0 was pip installed originally could you try a manual upgrade of ansible with
pip install --upgrade ansible==2.4.0 --disable-pip-version-check

**Comment by jvonau** [comment] 2017-10-24 22:49
> pip uninstall ansible got rid of it (I guess it wasn't a distro package)
now scripts/ansible runs

The script should of forced the upgrade via pip but I see that part needs work. I'll work at that part should time come up, although forcing the use of PPA does have an advantage. I'm thinking if the path to ansible is /usr/loca/bin/ then that is a pip install and proceed to pip uninstall before proceeding? Better as upgrade notes or scripted upgrades?

**Comment by holta** [comment] 2017-10-24 23:20
Thanks @tim-moody & @jvonau this clarifies a lot:

As such I've added `pip uninstall ansible` to STEP 5 of the official ["Do Everything from Scratch"](https://github.com/iiab/iiab/wiki/IIAB-Installation#do-everything-from-scratch) install instructions until the dust settles here.

Please everyone help articulate what's best: whether [scripts/ansible](https://github.com/iiab/iiab/blob/master/scripts/ansible) should include a PSA to help installers orient themselves when some weirdo new Ansible version/upgrading corner case hits them and/or whether they never will RTFM.  Regardless it seems wise (to me!) that scripts/ansible itself include a strong recommendation that folks at least be **aware** of the following URL before they proceed :-)

https://github.com/iiab/iiab/wiki/IIAB-Installation#do-everything-from-scratch

**Comment by holta** [comment] 2017-10-24 23:24
Ref #375

**Comment by jvonau** [comment] 2017-11-07 06:02
better feedback in #490

**Comment by jvonau** [comment] 2017-11-12 17:17
For the record the behaviour matched it's predecessor when ansible was already installed. 
> [root@box iiab]# scripts/ansible-2.2.0 
+ '[' x = xDEBUG -o x = xDEBUG ']'
++ which ansible-playbook
+ '[' '!' /bin/ansible-playbook ']'

**Comment by holta** [comment] 2017-11-12 17:57
Currently ./iiab-install warns if Ansible is missing or too old, per #509 built on #498.

So I'm closing this ticket.

**Closed as completed by holta** 2017-11-12 17:57 UTC
Labels: enhancement, question
