### ISSUE TITLE
ISSUE WHILE SAVING PERMITTED URLS [Admin Console, Squid]

### ISSUE THREAD

**Issue by vinaybissa** [iiab/iiab#1879] opened 2019-07-16 14:11 UTC
### Expected behavior and actual behavior.
Expected Behavior could be while saving the permitted urls it should whitelist those urls, but it return with error that SET -WHLIST generate a command error
### Steps to reproduce the problem.
After logging in to admin console and setting the permitted url it does not allow to save those url it returns with a error alert. (I have already set the IIAB GATEWAY True in Local Vars File)
### Specifications like the version of the IIAB, operating system version, or hardware details.
IIAB 7.0, Ubuntu 18.04 LTS, INTEL NUC

**Comment by holta** [comment] 2019-07-16 14:25
Thanks @vinaybissa for the report.

Can you provide the exact clicks/actions you took within IIAB's Admin Console (http://box.lan/admin) so others can reproduce this?

**Comment by vinaybissa** [comment] 2019-07-17 05:14
Step 1 - I opened the admin console with credentials (http://box.lan/admin)
Step 2 - I Clicked on Configure from Menus
Step 3 - From left navigation pane, i clicked on Edit Permitted Urls
Step 4 - In the section where i can enter the permitted urls, i entered one url (eg. http://www.domian.com)
Step 5- Then i Clicked on Update Permitted URls list

After this step i got error in alert box like this (SET-WHLIST FAILED and reported Unexpected error in Command SET-WHLIST)

**Comment by m-anish** [comment] 2019-07-17 08:30
Is squid/dansguardian installed?

I haven't been down that road in a while, so it may well be broken. 

Can you paste the output of:
```

/etc/iiab/iiab.env
/etc/iiab/iiab.ini
/etc/iiab/local_vars.yml
```

**Comment by m-anish** [comment] 2019-07-17 08:31
tagging @jvonau @tim-moody

**Comment by m-anish** [comment] 2019-07-17 08:32
FWIW, it looks like it may easily be possible with dnsmasq (if we're not already using it)
https://superuser.com/questions/625885/dns-block-all-websites-except-for-whitelisted-sites

**Comment by vinaybissa** [comment] 2019-07-17 09:48
Hi Anish - Seems SQUID/ DANSGUARDIAN Both are installed, PFA for your reference.

Regards
Vinay
________________________________

**Comment by vinaybissa** [comment] 2019-07-17 09:52
############ OUTPUT OF IIAB.ENV###########################
# This is a configuration file for IIAB
# It can be sourced in a shell script or read into an application
IIAB_BASE_PATH=/opt/iiab
IIAB_DIR=/opt/iiab/iiab
IIAB_RELEASE=7.0
IIAB_REVISION=0
IIAB_GATEWAY_ENABLED=True
LAN_IP=172.18.96.1
OS=ubuntu
OS_VER=ubuntu-18
WWWROOT=/library/www/html
STAGE=9
FQDN=box.lan
IIAB_USB_LIB_SHOW_ALL=True
IIAB_WAN_DEVICE="enp0s20u1"
IIAB_LAN_DEVICE="br0"
HOSTAPD_ENABLED=True
HTTPCACHE_ON=False


############ OUTPUT OF IIAB.INI###########################
[location]
iiab_base = /opt/iiab
iiab_dir = /opt/iiab/iiab
[version]
distribution = Ubuntu
arch = x86_64
iiab_base_ver = 7.0
iiab_branch = master
iiab_commit = 78e9a1f2c4e70245e99c9d1c7a079ec4361a4603
install_date = 2019-07-16T10:53:17Z
install_xo = none
[runtime]
iiab_stage = 9
iiab_base_ver = 7.0
iiab_revision = 0
runtime_php = /usr/lib/php
runtime_branch = master
runtime_commit = 78e9a1f2c4e70245e99c9d1c7a079ec4361a4603
runtime_date = 2019-07-17T09:40:05Z
ansible_version = 2.8.2
kernel = 4.15.0-54-generic
memory_mb = 5846
swap_mb = 2047
product_id = 3C611F00-732C-11E3-9115-F44D306D8FD5
gw_active = True
internet_available = True
is_rpi = False
first_run = False
local_tz = Asia/Kolkata
no_NM_reload = False
is_F18 = False
FQDN_changed = False
[iiab-admin]
name = iiab-admin
description = "Admin User"
iiab_admin_user = iiab-admin
[openvpn]
name = OpenVPN
description = OpenVPN enables live/remote support by connecting machines anywhere on the Internet, via a middleman server, using Virtual Private Network (VPN) techniques to create secure connections.
enabled = False
handle = 
cron_enabled = False
server = xscenet.net
server_virtual_ip = 10.8.0.1
server_port = 1194
[mysql]
name = MySQL
description = "MySQL is a widely used free and open source (GPLv2) database, offered by most web hosting services, on a diversity of platforms."
enabled = True
[usb-lib]
name = usb-lib
description = "usb-lib automounts Teacher Content on USB drives to /library/www/html/local_content, so students can browse it almost immediately at http://box/usb"
enabled = True
[elgg]
name = Elgg
description = "Elgg is an award-winning social networking engine, delivering the building blocks that enable businesses, schools, universities and associations to create their own fully-featured social networks and applications."
path = /opt/elgg
elgg_enabled = True
[Nextcloud]
name = Nextcloud
description = "NextCloud is a local server-based facility for sharing files, photos, contacts, calendars, etc."
path = /opt/nextcloud
nextcloud_orig_src_file = latest-16.tar.bz2
nextcloud_src_file = nextcloud_latest-16.tar.bz2
nextcloud_enabled = True
[wordpress]
name = WordPress
description = "WordPress is a blog and web site management application."
wordpress_src = latest.tar.gz
wp_abs_path = /library/wordpress
wp_db_name = iiab_wp
wp_db_user = iiab_wp
wp_url = /wordpress
wp_full_url = http://box/wordpress
wordpress_enabled = True
[kalite]
name = KA Lite
description = "KA Lite downloads Khan Academy videos for offline use, with exercises and accounts if students want to track their own progress."
path = /library/ka-lite
port = 8008
kalite_enabled = True
cron_enabled = True
[kiwix]
name = Kiwix
description = "Part of https://github.com/kiwix/kiwix-tools/ - kiwix-serve is the most used web server for ZIM files."
kiwix_url = /kiwix/
kiwix_path = /opt/iiab/kiwix
kiwix_port = 3000
iiab_zim_path = /library/zims
kiwix_library_xml = /library/zims/library.xml
kiwix_enabled = True
[mongodb]
name = MongoDB
description = "MongoDB is an open-source document database that provides high performance, high availability, and automatic scaling."
enabled = False
[sugarizer]
name = Sugarizer
description = "The Sugar Learning Platform began with the famous One Laptop Per Child project, written in Python. Sugarizer is the new HTML/JavaScript implementation of Sugar, usable in most all browsers."
sugarizer_enabled = True
[transmission]
name = transmission
description = "Transmission is a set of lightweight BitTorrent clients (in GUI, CLI and daemon form)."
transmission_install = True
transmission_enabled = True
transmission_download_dir = /library/transmission/
transmission_user = debian-transmission
transmission_group = root
transmission_http_port = 9091
transmission_url = /transmission/
transmission_peer_port = 51413
transmission_provision = True
transmission_kalite_version = 0.17
transmission_kalite_languages = 
transmission_username = Admin
transmission_password = changeme
[awstats]
name = AWStats
description = "AWStats (originally known as Advanced Web Statistics) is a package written in Perl which generates static or dynamic html summaries based upon web server logs."
installed = True
enabled = True
[munin]
name = Munin
description = "Munin is a networked resource monitoring tool that can help analyze resource trends and \"what just happened to kill our performance?\" problems."
installed = True
enabled = True
[vnstat]
name = vnStat
description = "vnStat is a console-based network traffic monitor for Linux and BSD that keeps a log of network traffic for the selected interface(s)."
installed = True
enabled = True
[detected_network]
has_ifcfg_gw = none
prior_gateway_(device_gw2) = "enp0s20u1"
dhcpcd_result = 
network_manager_active = False
systemd_networkd_active = True
wan_in_interfaces = False
wireless_list_1(wifi1) = not found-1
wireless_list_2(wifi2) = wlp2s0
num_wifi_interfaces = 1
discovered_wireless_iface = wlp2s0
discovered_wired_iface = enp0s25
num_lan_interfaces = 2
gui_static_wan = False
iiab_lan_iface = br0
iiab_wan_iface = enp0s20u1
[computed_network]
iiab_wan_enabled = True
user_wan_iface = enp0s20u1
iiab_wan_iface = enp0s20u1
iiab_lan_enabled = True
user_lan_iface = auto
iiab_lan_iface = br0
iiab_network_mode = Gateway
hostapd_enabled = True
host_ssid = Internet in a Box
host_wifi_mode = g
host_channel = 6
[network]
dansguardian_enabled = False
squid_enabled = False
wondershaper_enabled = False
iiab_network_mode_applied = Gateway
dhcpd_enabled = False
dhcp_service2 = dnsmasq
named_enabled = False
dnsmasq_enabled = True
no_net_restart = False
[squid]
enabled = False
name = Squid
description = "Squid caches web pages the first time they are accessed, and pulls them from the cache thereafter."
[dansguardian]
enabled = False
name = DansGuardian
description = "DansGuardian searches web content for objectionable references and denies access when found."
[wondershaper]
enabled = False
############ OUTPUT OF LOCAL_VARS.YML ###########################
# This is local_vars_medium.yml -- copy it to /etc/iiab/local_vars.yml then...
# modify variables below, to override /opt/iiab/iiab/vars/default_vars.yml

# PLZ READ http://wiki.laptop.org/go/IIAB/local_vars.yml AND http://FAQ.IIAB.IO
# Orig Idea: branch github.com/xsce/xsce-local for your deployment/community


# Ansible's default timeout for "get_url:" downloads (10 seconds) often fails
download_timeout: 200

# Languages (for Apache)
default_language: en
language_priority: en es fr

# Set iiab_admin_user_install: False if you don't want iiab_admin_user & wheel
# group auto-created in roles/iiab-admin/tasks/main.yml (hence disabling sudo-
# checks/warnings of published passwds like pi/raspberry & iiab-admin/g0adm1n).
iiab_admin_user_install: True
# If iiab_admin_user_install: False, set iiab_admin_user (below) to an existing
# Linux user that has sudo access, for login to Admin Console http://box/admin
iiab_admin_user: iiab-admin
# Password hash to be used if Ansible creates the above user:
iiab_admin_pwd_hash: $6$xsce51$D.IrrEeLBYIuJkGDmi27pZUGOwPFp98qpl3hxMwWV4hXigFGmdSvy3s/j7tn6OnyTTLmlV7SsN0lCUAFzxSop.
# Obtain a password hash - NEW MORE SECURE WAY:
#    python3 -c 'import crypt; print(crypt.crypt("<plaintext>", crypt.mksalt(crypt.METHOD_SHA512)))'
# Obtain a password hash - OLD WAY:
#    python -c 'import crypt; print crypt.crypt("<plaintext>", "$6$<salt>")'

iiab_hostname: box
iiab_domain: lan

# Homepage: set to /home or /wordpress or /mediawiki or /wiki (for DokuWiki)
iiab_home_url: /home

# Raspbian requires WiFi country since March 2018.  Please set it here:
host_country_code: US
host_ssid: "Internet in a Box"
host_wifi_mode: g
host_channel: 6
hostapd_secure: False
hostapd_password: changeme

# Enable "campus access" to ~10 common IIAB services like Kiwix (3000), KA Lite
# (8008) and Calibre (8010 or 8080) etc, on the WAN side of your IIAB server.
# Only 1 of the 6 lines below should be uncommented:
#
#ports_externally_visible: 0    # none
#ports_externally_visible: 1    # ssh only
#ports_externally_visible: 2    # ssh + http-or-https (for Admin Console's box.lan/admin too)
ports_externally_visible: 3     # ssh + http-or-https + common IIAB services
#ports_externally_visible: 4    # ssh + http-or-https + common IIAB services + Samba
#ports_externally_visible: 5    # all but databases
#
# Or further customize your iptables firewall by editing:
# /opt/iiab/iiab/roles/network/templates/gateway/iiab-gen-iptables
# And then run: cd /opt/iiab/iiab; ./iiab-network

# Make this True if client machines should have access to WAN/Internet:
iiab_gateway_enabled: True

dhcpd_install: False
dhcpd_enabled: False

# named (BIND)
named_install: False
named_enabled: False

# dnsmasq - handles DHCP and DNS
dnsmasq_install: True
dnsmasq_enabled: True

# Enable AFTER installing IIAB!  Then run "cd /opt/iiab/iiab; ./iiab-network"
dns_jail_enabled: False

# Python-based Captive Portal, that @m-anish & @jvonau experimented with in
# July 2018 (https://github.com/iiab/iiab/pull/870) and that @georgejhunt
# extensively refined later in 2018 (PRs #1179, #1300, #1327).
captive_portal_install: True
captive_portal_enabled: True
# In a pinch, disable Captive Portal using instructions in http://FAQ.IIAB.IO

# Set to "False" if you want to revert to the older Dynamic Menuing system
# (prior to IIAB 6.7, this had used https://github.com/iiab/iiab-menu)
js_menu_install: True

# Unmaintained as of October 2017: https://github.com/iiab/iiab/pull/382
# wondershaper_install: False
# wondershaper_enabled: False


# 1-PREP

# roles/sshd & roles/iiab-admin run here
# SEE IIAB-ADMIN VARIABLES NEAR TOP OF THIS FILE:
# e.g. iiab_admin_user_install, iiab_admin_user, iiab_admin_pwd_hash

# SECURITY WARNING: See http://wiki.laptop.org/go/IIAB/Security
openvpn_install: True
openvpn_enabled: False
# Set /etc/iiab/openvpn_handle in advance here:
openvpn_handle: 
# The following seems necessary on CentOS:
# openvpn_cron_enabled: True


# 2-COMMON

# exFAT_enabled: True is auto-enabled in roles/2-common/tasks/packages.yml
# as set in 0-init/defaults/main.yml AND 0-init/tasks/main.yml

# /usr/libexec/iiab-startup.sh is much like autoexec.bat & /etc/rc.local
# It's put in place by 2-common/tasks/iiab-startup.yml at the end of Stage 2.


# 3-BASE-SERVER

# Make this False to disable http://box/common/services/power_off.php button:
apache_allow_sudo: True
# For schools that use WordPress and/or Moodle intensively, see iiab/iiab #1147
# WARNING: Enabling this might cause excess use of RAM/disk or other resources!
apache_high_php_limits: False
# SEE ALSO VARIABLES NEAR TOP OF THIS FILE: default_language, language_priority

# roles/mysql runs here (mandatory)


# 4-SERVER-OPTIONS

# DNS prep (dnsmasq, named &/or dhcpd) run here.  The full network stage runs
# after 9-LOCAL-ADDONS (or manually run "cd /opt/iiab/iiab; ./iiab-network")

squid_install: True
squid_enabled: True

# DansGuardian REQUIRES Squid (above) be installed & enabled
dansguardian_install: True
dansguardian_enabled: True

# PostgreSQL - auto-installed by Moodle and/or Pathagar - no need to touch!
postgresql_install: False
postgresql_enabled: False

# Unmaintained
# authserver_install: False
# authserver_enabled: False

# Common UNIX Printing System (CUPS)
cups_install: False
cups_enabled: False

# At Your Own Risk: take a security audit seriously before deploying this
samba_install: False
samba_enabled: False

# Show entire contents of USB sticks/drives (at http://box/usb)
iiab_usb_lib_show_all: True


# 5-XO-SERVICES

# Lesser-supported XO services need additional testing.  Please contact
# http://lists.laptop.org/pipermail/server-devel/ if you're able to help test.

# xo_services_install: False
# xo_services_enabled: False

# activity_server_install: False
# activity_server_enabled: False

# Please instead consider 'ejabberd' in Stage 6-GENERIC-APPS below
# ejabberd_xs_install: False
# ejabberd_xs_enabled: False

# Change calibre_port from 8080 to 8010 below, if you enable idmgr
# idmgr_install: False
# idmgr_enabled: False


# 6-GENERIC-APPS

azuracast_install: False
azuracast_enabled: False

dokuwiki_install: False
dokuwiki_enabled: False

mediawiki_install: False
mediawiki_enabled: False

ejabberd_install: False
ejabberd_enabled: False

elgg_install: True
elgg_enabled: True

# Gitea (lightweight self-hosted "GitHub") from https://gitea.io
gitea_install: False
gitea_enabled: False

# Lokole (email for rural communities) from https://ascoderu.ca
lokole_install: False
lokole_enabled: False

# MQTT pub-sub broker for IoT on Raspberry Pi etc
mosquitto_install: False
mosquitto_enabled: False

# Flow-based visual programming for wiring together IoT hardware devices etc
nodered_install: False
nodered_enabled: False

nextcloud_install: True
nextcloud_enabled: True

# A full-featured PBX (for rural telephony, etc) based on Asterisk and FreePBX.
# Works on Ubuntu 18.04, Debian 9. Experimental on Rasp/RPi 3. Uses Node.js 10.x
pbx_install: False
pbx_enabled: False
asterisk_chan_dongle: False

# If using WordPress intensively, set apache_high_php_limits in 3-BASE-SERVER
wordpress_install: True
wordpress_enabled: True


# 7-EDU-APPS

# KA Lite - SEE THE "Transmission" BITTORRENT DOWNLOADER FURTHER BELOW, TO INSTALL THOUSANDS OF VIDEOS
kalite_install: True
kalite_enabled: True
# Unused in 2018; but remains as placeholder for Fedora 18 legacy (XO laptops)
kalite_cron_enabled: True

kolibri_install: False
kolibri_enabled: False

# kiwix_install: True is REQUIRED, if you install IIAB's Admin Console
kiwix_install: True
kiwix_enabled: True

# Warning: Moodle is a serious LMS, that takes a while to install
moodle_install: False
moodle_enabled: False
# If using Moodle intensively, set apache_high_php_limits in 3-BASE-SERVER

# Regional OSM vector maps use much less disk space than bitmap/raster versions
osm_vector_maps_install: True
osm_vector_maps_enabled: True

# Might stall MongoDB on Power Failure: github.com/xsce/xsce/issues/879
# Sugarizer 1.0.1+ strategies to solve? github.com/iiab/iiab/pull/957
# 2019-07-08 WARNING: both vars are IGNORED on Debian 10+ due to MongoDB: github.com/iiab/iiab/issues/1437
sugarizer_install: True
sugarizer_enabled: True


# 8-MGMT-TOOLS

# BitTorrent downloader for large Content Packs etc
transmission_install: True
transmission_enabled: True
# A. UNCOMMENT LANGUAGE(S) TO DOWNLOAD KA Lite VIDEOS TO /library/transmission
#    using http://pantry.learningequality.org/downloads/ka-lite/0.17/content/
transmission_kalite_languages:
  #- english
  #- french
  #- hindi
  #- portugal-portuguese
  #- brazilian-portuguese
  #- spanish
  #- swahili
# B. Monitor BitTorrent downloads at http://box:9091 using Admin/changeme
#    until the download is confirmed complete (can take hours if not days!)
# C. Carefully move all videos/thumbnails into /library/ka-lite/content
#    (DO NOT OVERWRITE SUBFOLDERS assessment, locale, srt !)
# D. Log in to KA Lite at http://box:8008/updates/videos/ using Admin/changeme
#    then click "Scan content folder for videos" (can take many minutes!)
# E. READ "KA Lite Administration: What tips & tricks exist?" AT http://FAQ.IIAB.IO

awstats_install: True
awstats_enabled: True

# 2019-07-08 WARNING: both vars are IGNORED on Debian 10+ due to: github.com/iiab/iiab/issues/1849
monit_install: False
monit_enabled: False

munin_install: True
munin_enabled: True

# Handy for maintaining tables, but DANGEROUS if not locked down
phpmyadmin_install: False
phpmyadmin_enabled: False

vnstat_install: True
vnstat_enabled: True


# 9-LOCAL-ADDONS

# Calibre E-Book Library
# WARNING: CALIBRE INSTALLS GRAPHICAL LIBRARIES SIMILAR TO X WINDOWS & OPENGL
# ON (HEADLESS, SERVER, LITE) OS'S THAT DON'T ALREADY HAVE THESE INSTALLED.
calibre_install: False
calibre_enabled: False
# Change calibre_port to 8010 if you're using XO laptops needing above idmgr ?
calibre_port: 8080
# Change calibre to XYZ to add your own mnemonic URL like: http://box/XYZ
calibre_web_path: calibre  #NEEDS WORK: https://github.com/iiab/iiab/issues/529
# Avoid URL collisions w/ calibreweb_url1, calibreweb_url2, calibreweb_url3 below!

# WARNING: Calibre-Web (below) depends on Calibre's own /usr/bin/ebook-convert
# program, so we recommend you also install Calibre (above!)

# Calibre-Web alternative to Calibre, offers a clean/modern UX
calibreweb_install: False
calibreweb_enabled: False
calibreweb_port: 8083       # PORT VARIABLE HAS NO EFFECT (as of January 2019)
# http://box/books works.  Add {box/libros, box/livres, box/livros, box/liv} etc?
calibreweb_url1: /books     # For SHORT URL http://box/books  (English)
calibreweb_url2: /libros    # For SHORT URL http://box/libros (Spanish)
calibreweb_url3: /livres    # For SHORT URL http://box/livres (French)
calibreweb_home: "{{ content_base }}/calibre-web"    # /library/calibre-web

# Internet Archive Decentralized Web - create your own offline version box:4244
# (or http://box/archive) arising from digital library https://dweb.archive.org
internetarchive_install: False
internetarchive_enabled: False

# Minetest is an open source clone of the Minecraft building blocks game
minetest_install: False
minetest_enabled: False


# CONSIDER THESE 2 NEW OPENSTREETMAP (OSM) APPROACHES INSTEAD, AS OF 2018:
# - http://download.iiab.io/content/OSM/vector-tiles/
# - http://oer2go.org/viewmod/en-worldmap-10
#
# DOWNLOAD EITHER OSM MANUALLY, OR BETTER YET TRY IIAB'S ADMIN CONSOLE:
#   http://box/admin -> Install Content -> Get OER2GO(RACHEL) Modules
#
# Unmaintained
# osm_install: False
# osm_enabled: False

# Unmaintained (better to install from http://teamviewer.com or prep scripts at http://download.iiab.io)
# teamviewer_install: False
# teamviewer_enabled: False

# Unmaintained
# docker_install: False
# docker_enabled: False

# Unmaintained
# schooltool_install: False
# schooltool_enabled: False

# Unmaintained
# debian_schooltool_install: False
# debian_schooltool_enabled: False

# Unmaintained (consider Calibre or Calibre-Web above?)
# pathagar_install: False
# pathagar_enabled: False

# Unmaintained
# sugar_stats_install: False
# sugar_stats_enabled: False

# Unmaintained
# xovis_install: False
# xovis_enabled: False

**Comment by holta** [comment] 2019-07-17 11:52
Thank @vinaybissa 

I hope @tim-moody can confirm today, and possibly offer alternatives.

**Comment by m-anish** [comment] 2019-07-17 13:59
@vinaybissa instead of copy pasting the contents, you can also attach a file on github :)

**Comment by holta** [comment] 2019-07-17 14:10
> @vinaybissa instead of copy pasting the contents, you can also attach a file on github :)

Usually this is easiest on everyone:

```
pastebinit < /etc/iiab/iiab.env
pastebinit < /etc/iiab/iiab.ini
pastebinit < /etc/iiab/local_vars.yml
```

In fact the command `/use/bin/iiab-diagnostics` handles this and more, if ever necessary!

**Comment by tim-moody** [comment] 2019-07-17 14:29
it will be looking for
/etc/squid3/sites.whitelist.txt
doubt this will be there unless squid is installed an enabled

**Comment by vinaybissa** [comment] 2019-07-18 06:31
@tim-moody  Squid is installed ,the files its looking for at this location
/etc/squid/sites.whitelist.txt not at what you mentioned earlier

As i can see the output of /etc/iiab/iian.ini, dansguardian and squid is not enable, how to make these services enabled

**Comment by tim-moody** [comment] 2019-07-18 12:27
OK. the problem is that iiab-admin-console maintains a varible squid_service that has 'squid3' for ubuntu, whereas iiab uses the variable proxy (could have a better name) that has 'squid'. 

 iiab-admin-console should use proxy

**Comment by holta** [comment] 2019-07-18 19:41
@vinaybissa can you review https://github.com/iiab/iiab-admin-console/pull/243 do see if that solves your problem?

As @tim-moody has now included into IIAB's mainline code.

Specifically, try the following:
- sudo su -
- cd /opt/iiab/iiab-admin-console
- git pull
- ./install

And then try again... (does this help?)

**Comment by vinaybissa** [comment] 2019-07-19 06:52
@holta  I have done that after installing the admin-console, now i am getting new error when opening admin-console, ERROR - [ GET-VARS FAILED and reported IIAB-CMDSRV failed to initialize]

**Comment by vinaybissa** [comment] 2019-07-19 08:48
@holta  & @tim-moody  - Issue has been resolved, but i am confused with the flow of given access to certain urls, to do this i have done steps as given below
Step 1- Logged in to Admin Console
Step 2 - Clicked on Configure -> Internet Filtering/Caching -> Checked (Restrict Web Page Access & Block all HTTPS Access ) so that i can access only few websites
Step 3- Then i clicked on Edit Permitted URL ( there are already many urls in the list)
Step 4-  I have added one more url at the end of the list.
Step 5-  Then i clicked upon Update Permitted Url list
Step 6 - Then i clicked save configuration
Step 7 - Then i clicked Install Configured Options
Step 8 - As it takes time to be successful state, so i waited for few minutes then it becomes successful.
Step 9 - After than i reboot the server
Step 10 - I have now internet access on my server, as i blocked all https sites so as usual they are not running, but i have given access to certain urls, but they are also not running.
Step 11- I reviewed the Edit Permit Url Section, as i can see the url i added in the end of list, they are not their only default entries are their, After running the Install Configured Option the list i have provided will be removed and the default entries remains.

**Comment by tim-moody** [comment] 2019-07-19 11:16
@vinaybissa can you try repeating steps 3 to 5 without the remaining steps and let us know what happened. I think step 7 reset your list.

**Comment by vinaybissa** [comment] 2019-07-19 11:23
@tim-moody By doing steps 3 to 5 i can see the latest added entries but still newly added urls are not accessible.

**Comment by tim-moody** [comment] 2019-07-19 11:27
@vinaybissa can you reboot just to be sure.

**Comment by vinaybissa** [comment] 2019-07-19 11:49
@tim-moody  rebooted the system, entries are updated, but still i am not able to access these url

**Comment by tim-moody** [comment] 2019-07-19 11:59
looks like a bug, squid or iiab. someone will have to investigate.

**Comment by tim-moody** [comment] 2019-07-19 12:11
to be clear are you trying to permit https://www.domain.com or http://www.domain.com?

what happens if you try to permit neverssl.com?

**Comment by vinaybissa** [comment] 2019-07-19 13:11
@tim-moody  i have added both type of entries ( 2 entries of https and 1 entry for http protocol) but none of them are working

**Comment by tim-moody** [comment] 2019-07-19 13:45
@vinaybissa any hint in /var/log/squid/access.log

**Comment by tim-moody** [comment] 2019-07-19 13:58
can you attach /etc/squid/sites.whitelist.txt

**Comment by jvonau** [comment] 2019-07-19 16:13
Can you post the contents of /etc/iiab/config_vars.yml please?

**Comment by holta** [comment] 2019-07-19 16:29
@vinaybissa consider running the `iiab-diagnostics` command to give us a more complete picture, as follows:
```
iiab-diagnostics /etc/squid/sites.whitelist.txt /var/log/squid/access.log
```
(If so, send us the resulting URL, thanks!)

**Comment by vinaybissa** [comment] 2019-07-20 07:04
@jvonau  here is the content of this file
http://paste.ubuntu.com/p/N3nmQNnHdM/

**Comment by vinaybissa** [comment] 2019-07-20 07:04
@tim-moody Please find attached for your reference
[sites.whitelist.txt](https://github.com/iiab/iiab/files/3413305/sites.whitelist.txt)

**Comment by vinaybissa** [comment] 2019-07-20 07:08
@holta  for your review
http://paste.ubuntu.com/p/3yfkWDCKXf/

**Comment by vinaybissa** [comment] 2019-07-20 07:11
Only thing i observed is it blocks all http urls weather they are in the sites.whitelist.txt or not. If i block all https web access from admin console then it blocks all https which is ok but the https url which i mentioned in sites.whitelist.txt should run but they are also not opening

**Comment by tim-moody** [comment] 2019-07-20 12:58
I think this logic is faulty:

{% if gw_squid_whitelist %}
http_access deny !whitelist
{% endif %}

http_access deny !Safe_ports
http_access allow school
http_access allow localhost
http_access deny all

to me this says block if not in whitelist and then later block all
it doesn't say allow whitelist

**Comment by tim-moody** [comment] 2019-07-20 13:02
@vinaybissa you could try editing /etc/squid/squid-iiab.conf and remove or comment out

http_access deny all

**Comment by jvonau** [comment] 2019-07-21 03:46
Think @tim-moody is on to something:
> 1563520151.855    729 127.0.0.1 TCP_DENIED/403 4251 GET http://quizacademy.org/ - HIER_NONE/- text/html

The source would be Dansgaurdian as shown by 127.0.0.1 as the source ip address in the log. The issue I see is in [squid-iiab.conf](https://github.com/iiab/iiab/blob/master/roles/network/templates/squid/squid-iiab.conf.j2) where the acl  for localhost is # out (line 38 #acl localhost src 127.0.0.1/32) so there would be no 'allow' present for that traffic.

The other issue is when 'save configuration' writes the whitelist file but as soon as 'Install Configured Options' is run [4-server-options](https://github.com/iiab/iiab/blob/master/roles/4-server-options/tasks/main.yml) is where [squid.yml](https://github.com/iiab/iiab/blob/master/roles/network/tasks/squid.yml) is referenced and we supply a new template for whitelist.txt, wiping out the user's custom settings.

**Comment by jvonau** [comment] 2019-07-21 05:02
> but the https url which i mentioned in sites.whitelist.txt should run but they are also not opening

The block https is done in iiab-gen-iptables also. 
`if [ "$gw_block_https" == "True" ]; then $IPTABLES -A FORWARD -p tcp ! -d {{ lan_ip }} --dport 443 -j DROP fi`

That makes blocking all or none, I don't think squid is currently setup to handle https requests, and would be missing the iptable rule for the interception.

**Comment by holta** [comment] 2019-07-21 11:46
@vinaybissa, I've merged in @jvonau's change here, so that you can immediately test if and what this improves:

_PR #1893 Don't force templates, only create once in squid.yml_

To test this, I believe you need to run the following:
```
sudo su -
cd /opt/iiab/iiab
git pull
./runrole 4-server-options
```
And it probably doesn't hurt to then also run:
```
./iiab-network
```
And then test filtering of your `http` sites (remembering that all `https` sites are blocked for now!)

**Comment by tim-moody** [comment] 2019-07-21 20:43
this fixes a secondary problem, but the primary

**Comment by holta** [comment] 2019-07-22 14:50
> this fixes a secondary problem, but the primary

What should we move towards releasing here?

@vinaybissa can you provide feedback on the several questions & recommendations @tim-moody & @jvonau posed over the weekend?

**Comment by holta** [comment] 2019-07-24 09:58
> @vinaybissa you could try editing /etc/squid/squid-iiab.conf and remove or comment out
> 
> http_access deny all

@vinaybissa what is the result please, when you try this?

(Not sure if a reboot is required or not!)

**Comment by vinaybissa** [comment] 2019-08-01 05:39
> @vinaybissa you could try editing /etc/squid/squid-iiab.conf and remove or comment out
> 
> http_access deny all

@tim-moody - i have tried this now its filtering url having http, but what about https url ?

**Comment by vinaybissa** [comment] 2019-08-01 05:39
> > @vinaybissa you could try editing /etc/squid/squid-iiab.conf and remove or comment out
> > http_access deny all
> 
> @vinaybissa what is the result please, when you try this?
> 
> (Not sure if a reboot is required or not!)

@holta . Its working fine now for filtering http urls, but is there any way to filter https url ?

**Comment by jvonau** [comment] 2019-08-01 06:05
> > @vinaybissa you could try editing /etc/squid/squid-iiab.conf and remove or comment out
> > http_access deny all
> 
> @tim-moody - i have tried this now its filtering url having http, but what about https url ?

Did you apply the git pull/fix as recommended above first? Disabling 'deny all' is not really recommended by [upstream](http://www.squid-cache.org/Doc/config/http_access/). About https, as explained above. Did you have a feature request and time to test? In the end which websites do you want direct access to?

**Comment by vinaybissa** [comment] 2019-08-01 08:05
> > > @vinaybissa you could try editing /etc/squid/squid-iiab.conf and remove or comment out
> > > http_access deny all
> > 
> > 
> > @tim-moody - i have tried this now its filtering url having http, but what about https url ?
> 
> Did you apply the git pull/fix as recommended above first? Disabling 'deny all' is not really recommended by [upstream](http://www.squid-cache.org/Doc/config/http_access/). About https, as explained above. Did you have a feature request and time to test? In the end which websites do you want direct access to?

@jvonau - i have done with process which you described, now filtering is working for http urls, but still issue with https (Interestingly Youtube and sugarlabs.org which are hosted on https are working, rest https are not working)

**Comment by holta** [comment] 2019-08-01 14:14
Thanks @vinaybissa!  Can you also:
1. tell us if the youtube videos are actually playing?
2. reboot
3. test both kinds of https sites (those that were blocked and those that were not like youtube.com & sugarlabs.org)
4. re-run /usr/bin/iiab-diagnostics and then post the resulting URL ?

**Comment by holta** [comment] 2019-12-21 12:52
> Thanks @vinaybissa! Can you also:
> 
> 1. tell us if the youtube videos are actually playing?
> 2. reboot
> 3. test both kinds of https sites (those that were blocked and those that were not like youtube.com & sugarlabs.org)
> 4. re-run /usr/bin/iiab-diagnostics and then post the resulting URL ?

@vinaybissa can you confirm where you're at?

Or should I close this now?

Thanks!

**Comment by holta** [comment] 2021-08-24 14:14
@vinaybissa IIAB's Squid implementation was overhauled over the last 10 days, so please do try it out if this is still useful to you?  

Thanks for your input if you have a moment!

Quick summary of the changes:

1. https://github.com/iiab/iiab/blob/master/roles/network/templates/squid/squid.conf.j2
2. PR #2948
3. PR #2963

(Finally, feel free to re-open this or another ticket if necessary!)

**Closed as completed by holta** 2021-08-24 14:14 UTC
Labels: bug, question, admin console
