### ISSUE TITLE
Kiwix install fails as part of install of current master [segmentation fault, due to Raspbian or Ubuntu 19.10 kernel on RPi]

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab#1993] opened 2019-10-08 20:52 UTC
TASK [kiwix : Enable & Restart 'kiwix-serve' service] ****************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unable to restart service kiwix-serve: Job for kiwix-serve.service failed because a fatal signal was delivered to the control process.\nSee \"systemctl status kiwix-serve.service\" and \"journalctl -xe\" for details.\n"}

**Comment by tim-moody** [comment] 2019-10-08 20:53
fails again on rerun of install

**Comment by tim-moody** [comment] 2019-10-08 20:54
but the services is actually running

**Comment by tim-moody** [comment] 2019-10-08 20:55
ran a third time and it succeeded

**Comment by tim-moody** [comment] 2019-10-08 20:58
```
-- A start job for unit kiwix-serve.service has begun execution.
--
-- The job identifier is 2362.
Oct 08 21:16:11 box.lan systemd[1]: kiwix-serve.service: Control process exited, code=killed, status=11/SEGV
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit kiwix-serve.service has exited.
--
-- The process' exit code is 'killed' and its exit status is 11.
Oct 08 21:16:11 box.lan systemd[1]: kiwix-serve.service: Failed with result 'signal'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit kiwix-serve.service has entered the 'failed' state with result 'signal'.
Oct 08 21:16:11 box.lan systemd[1]: Failed to start Provides the Kiwix ZIM File Server.
-- Subject: A start job for unit kiwix-serve.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit kiwix-serve.service has finished with a failure.
--
-- The job identifier is 2362 and the job result is failed.
Oct 08 21:16:16 box.lan systemd[1]: kiwix-serve.service: Service RestartSec=5s expired, scheduling restart.
Oct 08 21:16:16 box.lan systemd[1]: kiwix-serve.service: Scheduled restart job, restart counter is at 1.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit kiwix-serve.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Oct 08 21:16:16 box.lan systemd[1]: Stopped Provides the Kiwix ZIM File Server.
-- Subject: A stop job for unit kiwix-serve.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit kiwix-serve.service has finished.
--
-- The job identifier is 2420 and the job result is done.
Oct 08 21:16:16 box.lan systemd[1]: Starting Provides the Kiwix ZIM File Server...
-- Subject: A start job for unit kiwix-serve.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit kiwix-serve.service has begun execution.
--
-- The job identifier is 2420.
Oct 08 21:16:16 box.lan systemd[1]: Started Provides the Kiwix ZIM File Server.
-- Subject: A start job for unit kiwix-serve.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit kiwix-serve.service has finished successfully.
--
-- The job identifier is 2420.
root@raspberrypi:/opt/iiab/iiab# systemctl status kiwix-serve
● kiwix-serve.service - Provides the Kiwix ZIM File Server
   Loaded: loaded (/etc/systemd/system/kiwix-serve.service; enabled; vendor preset: enabled)
   Active: active  since Tue 2019-10-08 21:16:16 BST; 1min 21s ago
  Process: 32088 ExecStart=/opt/iiab/kiwix/bin/kiwix-serve --daemon --port 3000 --nolibrarybutton --library /library/zims/library.xml --urlRootLocation=/kiwix/ (code=exited, status=0/SUCCESS
 Main PID: 32089 (kiwix-serve)
    Tasks: 5 (limit: 4035)
   Memory: 1.6M
   CGroup: /system.slice/kiwix-serve.service
           └─32089 /opt/iiab/kiwix/bin/kiwix-serve --daemon --port 3000 --nolibrarybutton --library /library/zims/library.xml --urlRootLocation=/kiwix/

**Comment by tim-moody** [comment] 2019-10-08 20:58
the question is what killed it early in the process

**Comment by holta** [comment] 2019-10-08 20:58
Someone else experienced much the same last week I believe?

Does **/etc/systemd/system/kiwix-serve.service** need improvement? (from https://github.com/iiab/iiab/blob/master/roles/kiwix/templates/kiwix-serve.service.j2)

FYI @tim-moody is running Raspbian Lite 2019-09-26 on a RPi 4 with 2GB RAM.

**Comment by jvonau** [comment] 2019-10-09 04:02
status=11/SEGV suggests segmentation fault, that would be in the binary provided by upstream.

**Comment by tim-moody** [comment] 2019-10-09 12:07
I'll raise an issue.

**Comment by holta** [comment] 2019-10-09 12:21
Almost identical problem happened to someone else last week, also with kiwix-tools 3.0.1-6 as released in IIAB 7.0

> I'll raise an issue.

Thanks @tim-moody 

What's the upstream tkt when you can?

**Comment by tim-moody** [comment] 2019-10-09 12:26
kiwix/kiwix-tools#341

**Comment by tim-moody** [comment] 2019-10-09 13:00
opened kiwix/kiwix-tools#341

**Comment by holta** [comment] 2019-10-10 20:46
Ideas:

1) @jvonau suggests we use Ansible's `ignore_errors: yes` for now, until kiwix-tools is fixed.

   Reason: kiwix-serve is eventually started (by its systemd unit file, after several attempts) so the initial failure to start can safely be ignored it seems.

2) @jvonau suggests adding `ExecStopPost=/bin/sleep 10` under the `ExecStart=` line in [/etc/systemd/system/kiwix-serve.service](https://github.com/iiab/iiab/blob/master/roles/kiwix/templates/kiwix-serve.service.j2) &mdash; and then testing by running `systemtl daemon-reload` and then `systemctl restart kiwix-serve`

3) @tim-moody asks if kiwix-tools 2.0.0 or 2.1.0 might work better than 3.0.1-6 ??

4) Several are asking if the very recent Raspbian 2019-09-26 [published around 2019-10-01] or its subsequent apt updates libraries/dependencies (or a new kernel) might be underlying this problem...

Tangentially Related:

#1997 Have some kind of watchdog for kiwix [beyond our current cron job?]

**Comment by holta** [comment] 2019-10-11 12:40
Root cause might be this upstream Raspbian issue: raspberrypi/linux#3271 (thx @tim-moody)

**Comment by jvonau** [comment] 2019-10-11 16:30
Think raspberrypi/linux#3279 is the root cause due to raspberrypi/linux@c0ccb4d

**Comment by holta** [comment] 2019-10-11 23:04
The fix is in &mdash; running `rpi-update` to get pre-release kernel 4.19.79-v7l+ (instead of 4.19.75-v7l+ released yesterday and again today!) somehow does the trick: https://github.com/raspberrypi/linux/issues/3271#issuecomment-541250165

But it might take a few days to be published/mainlined by the Raspberry Pi Foundation, so that everyone will be able to fix things by running...

```
apt update && apt -y dist-upgrade && reboot
```

**Comment by holta** [comment] 2019-10-13 00:31
@jvonau points out we can watch for new kernel packages here:

http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/

(Or run `apt update`)

**Comment by jvonau** [comment] 2019-10-29 15:49
We should really not waste potential users time by forcing a broken kernel to be installed as part of 'iiab' https://github.com/iiab/iiab-factory/pull/84

**Comment by holta** [comment] 2019-10-29 17:14
I've widely published community warnings (on mailing lists etc) that it's as simple as running `rpi-update` to fix the kernel problem -- in the interim until Raspbian finally gets their new kernel mainlined into apt / etc -- hopefully very soon now!

Thanks to @jvonau who provided this link so we can track that upcoming kernel release, which should appear here soon:
http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/?C=M;O=D

Recap: this issue is annoying but under control, which an easy-as-cake workaround that even non-technical implementers find wonderfully straightforward and fast.  But perhaps things like iiab/iiab-factory#84 can message this warning even more broadly, if that's easy to do?

**Comment by holta** [comment] 2019-10-29 17:17
If we automate this warning, it should probably say something like:

> Please now run 'rpi-update' to install an experimental Raspbian kernel/firmware at your own risk.  This is needed because of ABC.  After reboot, please then do XYZ...

**Comment by tim-moody** [comment] 2019-10-29 17:25
my concern is whether we should trust this patch for production environments. if not what is the alternative?

**Comment by holta** [comment] 2019-10-29 17:37
> my concern is whether we should trust this patch for production environments. if not what is the alternative?

Yep.  The patch (just run `rpi-update`) has been working for almost ~3 weeks so far, but having it blessed as an official Raspbian apt update (or [published Raspbian release](https://www.raspberrypi.org/downloads/raspbian/)) would be better.

**Comment by holta** [comment] 2019-10-29 17:46
FWIW the `rpi-update` critical patch is helping a lot of people out there...hopefully the Rasp Pi Fdtn will take notice and finally push it making it more official soon:

https://github.com/weaveworks/weave/issues/3717#issuecomment-547545459

**Comment by jvonau** [comment] 2019-10-30 06:07
The big unknown is what happens when apt finally updates a kernel on a machine where rpi-update was run, 'should be fine' (famous words to be burnt by) but my crystal ball is foggy. I'd rather run an older working kernel than do the 'apt update'/rpi-update dance. My general take is rpi-update should never be used unless asked to by an upstream developer as a debugging tool for their end of the code, it's an easy to used tool for them to deploy patches for testing. This now introduces another variable in that what was installed yesterday can differ with what will be installed today. Given the fix appeared in '1273' but now '1274' appeared in rpi-update with new code and potential regressions to debug as this method is a fast moving target. I'd prefer not to force the full dist-upgrade and install a broken kernel. 

> my concern is whether we should trust this patch for production environments. if not what is the alternative? 

Funny you should ask, we do have ready made images I did up for 7.0 dated Oct 8, frozen in time before the kernel issue cropped up. Those images can also be used with master (much better once installed branch hit master) and I'm working with Adam for the needed code to 'iiab' for one question y|n to make that happen.

**Comment by holta** [comment] 2019-11-05 19:54
@tim-moody observed this same kiwix problem on Ubuntu 19.10 (32-bit) on RPi 4:

> TASK [kiwix : Enable & Restart 'kiwix-serve' service] ****************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Unable to start service kiwix-serve: Job for kiwix-serve.service failed because a fatal signal was delivered causing the control process to dump core.\nSee \"systemctl status kiwix-serve.service\" and \"journalctl -xe\" for details.\n"}

Is the very latest Linux kernel necessary for 19.10 as well as for Raspbian?

**Comment by jvonau** [comment] 2019-11-14 17:29
#2025 is forcing the use of rpi-update

**Comment by holta** [comment] 2019-11-14 20:02
> http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/?C=M;O=D

A reminder that kernel packages available via apt can be tracked above.

In addition, new Raspbian releases can be tracked here:
https://downloads.raspberrypi.org/raspbian_lite/images/?C=M;O=D

**Comment by holta** [comment] 2019-11-19 14:37
As mentioned on https://github.com/raspberrypi/linux/issues/3271#issuecomment-555531053

...the next version of Raspbian is likely...

> waiting for something new to show up on https://github.com/raspberrypi/firmware/commits/stable/

**Comment by holta** [comment] 2020-01-22 04:26
Finally a new kernel appeared 3+ months later in Raspbian `apt` update process:

```
root@box:~# uname -a
Linux box.lan 4.19.93-v7l+ #1290 SMP Fri Jan 10 16:45:11 GMT 2020 armv7l GNU/Linux
```

Also confirmed by:
http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/?C=M;O=D)

...so I'm closing this ticket (hurrah the `rpi-update` command is no longer necessary at this time!)

PS quite likely new Raspbian ISO / .img images will be published here shortly in coming weeks if not days: https://www.raspberrypi.org/downloads/raspbian/ (for those who don't like to wait for apt updates :)

**Closed as completed by holta** 2020-01-22 04:26 UTC
Labels: bug, question
